version: '3.7'
services:
  web:
    image: nginx:1.17.9-alpine
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_PORT=80
    volumes:
      - ./deploy/web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./deploy/web/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx
      - ./wwwroot:/www
  phpfpm:
    build: ./wwwroot
    image: blldxt/learn-phpfpm:1.0
    working_dir: /www
    expose: 
      - 9000
    volumes:
      # - ./deploy/phpfpm/php.ini:/usr/local/etc/php/php.ini
      - ./deploy/phpfpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./wwwroot:/www
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: blldxt
    expose:
      - 3306
    volumes:
      - ./deploy/db/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3306
      PMA_HOST: db
    ports:
      - 8080:80
